### ISSUE TITLE
path included in image file name display

### ISSUE THREAD

**Issue by lostonroute66** [HHS/pillbox-engine#35]
In Compare, Images, why is "pillbox/" included with the image filename for both SPL and Pillbox values?

**Comment by ghost** [comment]
Still seeing "pillbox/" in the export file with the splimage filenames.  Confirmed with record where image is coming from the label in DailyMed.

51618,True,2017-08-08T19:58:27.140414+00:00,2017-08-09T21:12:33.804134+00:00,2cec3d3d-21d9-476c-e054-00144ff88e88-69618-014-0,2cec3d3d-21d9-476c-e054-00144ff88e88,8,,C48348,ROUND,,1,,AP;009,,C48331,ORANGE,,ASPIRIN 81 mg;,ASPIRIN[ASPIRIN];,"STARCH, CORN;SILICON DIOXIDE;SUCROSE;FD&C YELLOW NO. 6;MAGNESIUM STEARATE;ORANGE;",HOTC,SCD,Aspirin 81 MG Chewable Tablet,318272,2017-08-09T20:29:34.076862+00:00,69618-014,0,,696180014,69618,014,Aspirin 81 mg,active,20160316,2e3095a3-99fc-183f-e054-00144ff88e88.xml,,C42893,,,,LABELER,Reliable 1 Laboratories LLC,C73603,SPL,pillbox/2e1bf7fd-929f-53e5-e054-00144ff8d46c.jpg,True,,2,,,True,False,False,False

**Comment by scisco** [comment]
Confirming this is still an issue. Will issue a fix soon.

**Comment by scisco** [comment]
this should be fixed now.
