### ISSUE TITLE
RxNorm process issues

### ISSUE THREAD

**Issue by lostonroute66** [HHS/pillbox-engine#58]
Several runs in a row have hung at about the same place.  The last change to rxnorm.py was 15 days ago. I've done 2 successful processes already with the current code.  I'm putting info here while I investigate.

action: rxnom sync |total: 38724 |percent: 86.65 |processed: 33553 |     Dec. 26, 2014, 8:53 p.m.
action: rxnom sync |total: 38724 |percent: 86.94 |processed: 33668 |     Dec. 26, 2014, 11:22 p.m.
action: rxnom sync |total: 38724 |percent: 87.97 |processed: 34066 |    Dec. 27, 2014, 12:42 a.m.
action: rxnom sync |total: 38724 |percent: 87.43 |processed: 33858 |    Dec. 27, 2014, 1:12 a.m.

I'm checking with the RxNorm team to see if there's anything useful in the logs.  They've already said there are no bandwidth limits on the API.

This is the first time I've run the RxNorm process since the several updates that were done this week.

It could be an issue with my home ISP.  Have to wait and test at another connection.  The only other change to my system was the NTP security update Apple pushed earlier this week, though I'm not sure how chicness to NTP could affect this.  https://support.apple.com/en-us/HT6601

And of course I've rebooted and restarted the database and virtualenv.

**Comment by ghost** [comment]
After testing and discussion with the RxNorm team we determined the script is exceeding the RxNorm API usage limits (20/second http://rxnav.nlm.nih.gov/TermOfService.html).

We're testing code that will wait after a certain number of threads.

**Comment by ghost** [comment]
Attached code from RxNorm team (based on https://github.com/HHS/pillbox-engine/blob/923f3f54145e56b41a5b06214303aca7ea126246/pillbox-engine/spl/sync/rxnorm.py) does the following.
1) added a sleep after a certain number of thread creations (default=20)
2) replaced your two API calls to get TTY and String with a single call (/properties)

Didn't run when tested.

**Comment by lostonroute66** [comment]
import sys
import requests
import simplejson as json
import string
import threading
import time

class myThread (threading.Thread):
    def __init__(self, threadID, name):
        threading.Thread.__init__(self)
        self.threadID = threadID
        self.name = name
    def run(self):
        idfound = rxnorm(self.name)
        print "%s data: %s" % (self.threadID, idfound)

def rxnorm(ndc):
    if ndc[0] is None:
        return {"rxcui": "", "rxtty": "", "rxstring": ""}
    else:
        try:
#            baseurl = 'http://rxnavstage.nlm.nih.gov/REST/'
            baseurl = 'http://mor3.nlm.nih.gov/RxNormRest/'

            # Searching RXNorm API, Search by identifier to find RxNorm concepts
            # http://rxnav.nlm.nih.gov/REST/rxcui?idtype=NDC&id=0591-2234-10
            # Set url parameters for searching RXNorm for SETID
            ndcSearch = 'rxcui?idtype=NDC&id='
            # Search RXNorm API, Return all properties for a concept
            rxPropSearch = 'rxcui/'
#            rxttySearch = '/property?propName=TTY'
#            rxstringSearch = '/property?propName=RxNorm%20Name'
	    rxconceptSearch = '/properties'

            # Request RXNorm API to return json
            header = {'Accept': 'application/json'}

#            def getTTY(rxCUI):
#                # Search RXNorm again using RXCUI to return RXTTY & RXSTRING
#                getTTY = requests.get(baseurl+rxPropSearch+rxCUI+rxttySearch, headers=header)
#
#                ttyJSON = json.loads(getTTY.text, encoding="utf-8")
#
#                return ttyJSON['propConceptGroup']['propConcept'][0]['propValue']
#
#            def getSTRING(rxCUI):
#                # Search RXNorm again using RXCUI to return RXTTY & RXSTRING
#                getString = requests.get(baseurl+rxPropSearch+rxCUI+rxstringSearch, headers=header)
#                stringJSON = json.loads(getString.text, encoding="utf-8")
#                return stringJSON['propConceptGroup']['propConcept'][0]['propValue']
#
            def getProps(rxCUI):
                # get the concept properties 
                getProps = requests.get(baseurl+rxPropSearch+rxCUI+rxconceptSearch, headers=header)
                propsJSON = json.loads(getProps.text, encoding="utf-8")
                print "propsJSON %s" % propsJSON
		return propsJSON

            # Search RXNorm using NDC code, return RXCUI id
            getRXCUI = requests.get(baseurl+ndcSearch+ndc, headers=header)
            if getRXCUI.status_code != requests.codes.ok:
                print "RXNorm server response error. Response code: %s" % getRXCUI.status_code
            rxcuiJSON = json.loads(getRXCUI.text, encoding="utf-8")
            # Check if first value in list returns a RXCUI, if not go to next value
            try:
                if rxcuiJSON['idGroup']['rxnormId']:
                    rxCUI = rxcuiJSON['idGroup']['rxnormId'][0]
		    propsJSON = getProps(rxCUI)
		    rxTTY = propsJSON['properties']['tty']
		    rxSTRING = propsJSON['properties']['name']
#                    rxTTY = getTTY(rxCUI)
#                    rxSTRING = getSTRING(rxCUI)
                    return {"rxcui": rxCUI, "rxtty": rxTTY, "rxstring": rxSTRING}
            except KeyError:
                # if last item return null values
                return {"rxcui": "", "rxtty": "", "rxstring": ""}

        except:
            print "Exception found"
            return {"rxcui": "", "rxtty": "", "rxstring": ""}
           # sys.exit("RXNorm connection")

if __name__ == "__main__": 
#   comand list arguments:  filename maxcount
#        where
#               filename - input file of NDCs, one per line
#               maxcount - (optional) maximum processing before delay
#
    arglen = len(sys.argv)
    if arglen < 2:
        sys.exit("ERROR: no command arguments specified\n Format: test2.py filename [maxcount]")
    inputfilename = sys.argv[1]
#   maxcount is the number of threads to create before pausing
    maxcount = 20
    if arglen > 2:
        maxcount = string.atoi(sys.argv[2])
    inputfile = open(inputfilename,"r")
    print time.ctime(time.time())
    count = 0
    while 1:
        ndc = inputfile.readline();
        if not ndc:
            break
        count += 1
        rem = count % maxcount
        if rem < 1:
            print "Sleeping for one second";
            time.sleep(1)
        thr = myThread ( count, ndc[:-1] )
#        idfound = rxnorm(ndc[:-1])
        thr.start()
    time.sleep(1)
    print time.ctime(time.time())

**Comment by ghost** [comment]
[test2.py.txt](https://github.com/HHS/pillbox-engine/files/153656/test2.py.txt)
